version: "3.8"
services:
  neo4j:
    image: neo4j:5.13
    container_name: neo4j
    environment:
      NEO4J_AUTH: "none"     # désactive l'authentification pour simplifier
      NEO4J_dbms_memory_pagecache_size: "1G"
      NEO4J_dbms_memory_heap_max__size: "2G"
    ports:
      - "7474:7474"   # HTTP / Browser
      - "7687:7687"   # Bolt (driver)
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/import:/var/lib/neo4j/import
    restart: unless-stopped
